language: node_js
node_js: 
  - stable
script:
  - npm install
  - npm run build
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true 
  keep_history: false
  local_dir: dist

  on:
    branch: master